app_name: "NVCLab"
app:
  app_version: "1.0.0"
  example_key:
    key: "example_value"

logging:
  console:
    enabled: true
    format: "<green>{time}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    level: "INFO"
    time_format: "YYYY-MM-DD HH:mm:ss.SSS"
  file:
    enabled: false
    file_path: "logs/app_{time:YYYY-MM-DD}.log"
    format: "{time:YYYY-MM-DD HH:mm:ss.SSS} | {level} | {message}"
    level: "INFO"
    rotation: "10 MB"
    compression: "zip"
    time_format: "YYYY-MM-DD HH:mm:ss.SSS"